name: haoyang
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - archspec=0.2.1=pyhd3eb1b0_0
  - boltons=23.0.0=py311h06a4308_0
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.11.0=py311h06a4308_0
  - conda-content-trust=0.2.0=py311h06a4308_0
  - conda-libmamba-solver=23.12.0=pyhd3eb1b0_1
  - conda-package-handling=2.2.0=py311h06a4308_0
  - conda-package-streaming=0.9.0=py311h06a4308_0
  - cryptography=41.0.7=py311hdda0065_0
  - distro=1.8.0=py311h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_2
  - libcurl=8.4.0=h251f7ec_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.3=haf1ee3a_0
  - libmambapy=1.5.3=py311h2dafd23_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_0
  - menuinst=2.0.1=py311h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py311h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py311h06a4308_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - truststore=0.8.0=py311h06a4308_0
  - urllib3=1.26.18=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py311h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.48.1
      - fsspec==2024.2.0
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.0
      - pillow==10.2.0
      - plyfile==1.0.3
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2024.1
      - six==1.16.0
      - sympy==1.12
      - torch==2.2.0
      - torchvision==0.17.0
      - triton==2.2.0
      - typing-extensions==4.9.0
      - tzdata==2023.4